#!/bin/bash

# Ensure script is sourced
if [ "$0" = "$BASH_SOURCE" ]; then
    echo "❌ Error: You must SOURCE this script!"
    echo "Use: source updated_setup.sh"
    exit 1
fi

echo "=== BeagleBone Black Yocto Setup Script ==="
echo ""
echo "Choose Kernel Version:"
echo "1) Kernel 6.x (TI Staging)"
echo "2) Kernel 7.x (Mainline)"
echo -n "Enter your choice (1 or 2): "
read -r choice

ROOT_DIR=$(pwd)

case $choice in
    1)
        BUILD_DIR="build-k6"
        KERNEL_PROVIDER="linux-ti-staging"
        KERNEL_VERSION="6"
        # Combine TI paths on a single space-separated line
        EXTRA_LAYERS="${ROOT_DIR}/poky/meta-ti/meta-ti-bsp ${ROOT_DIR}/poky/meta-ti/meta-ti-extras"
        echo "Selected: Kernel 6.x (TI Staging)"
        ;;
    2)
        BUILD_DIR="build-k7"
        KERNEL_PROVIDER="linux-mainline"
        KERNEL_VERSION="7"
        # Single path for kernel 7
        EXTRA_LAYERS="${ROOT_DIR}/poky/meta-linux-kernel7.0"
        echo "Selected: Kernel 7.x (Mainline)"
        ;;
    *)
        echo "Invalid choice!"
        return 1 2>/dev/null || exit 1
        ;;
esac

export TEMPLATECONF=${ROOT_DIR}/poky/meta-custom/conf/templates/bbb

echo "Initializing build environment: $BUILD_DIR ..."
source poky/oe-init-build-env $BUILD_DIR

echo "Fixing bblayers.conf..."

# Write everything on a single clean line to guarantee flawless parsing
cat > conf/bblayers.conf << EOL
# Auto-generated by setup.sh
LCONF_VERSION = "7"

BBLAYERS ?= "${ROOT_DIR}/poky/meta ${ROOT_DIR}/poky/meta-poky ${ROOT_DIR}/poky/meta-yocto-bsp ${ROOT_DIR}/poky/meta-arm/meta-arm ${ROOT_DIR}/poky/meta-arm/meta-arm-toolchain ${ROOT_DIR}/poky/meta-openembedded/meta-oe ${ROOT_DIR}/poky/meta-openembedded/meta-python ${ROOT_DIR}/poky/meta-openembedded/meta-networking ${ROOT_DIR}/poky/meta-custom ${EXTRA_LAYERS}"

BBLAYERS_NON_REMOVABLE ?= "${ROOT_DIR}/poky/meta ${ROOT_DIR}/poky/meta-poky"
EOL

# Fix local.conf
sed -i '/# === START GENERATED KERNEL CONFIG ===/,/# === END GENERATED KERNEL CONFIG ===/d' conf/local.conf 2>/dev/null || true

cat >> conf/local.conf << EOL

# === START GENERATED KERNEL CONFIG ===
MACHINE = "beaglebone-yocto"
PREFERRED_PROVIDER_virtual/kernel = "${KERNEL_PROVIDER}"

BB_NUMBER_THREADS ?= "\${@oe.utils.cpu_count()}"
PARALLEL_MAKE ?= "-j \${@oe.utils.cpu_count()}"
# === END GENERATED KERNEL CONFIG ===
EOL

if [ "$choice" = "2" ]; then
    cat >> conf/local.conf << EOL
PREFERRED_VERSION_linux-mainline = "7.0%"
KERNEL_DEVICETREE = "ti/omap/am335x-bone.dtb ti/omap/am335x-boneblack.dtb"
EOL
fi

echo ""
echo "===================================================="
echo "✅ Setup completed successfully!"
echo "Build Directory : \$(pwd)"
echo "Kernel          : ${KERNEL_VERSION}.x"
echo "===================================================="
